const baseItems = [
  { emoji:'🍟', name:'Batata frita', description:'Crocante e perfeita para dividir', quantity:true },
  { emoji:'🥤', name:'Refrigerante', description:'Para brindar nosso momento', quantity:true },
  { emoji:'🍫', name:'Chocolate', description:'Um docinho para adoçar a noite', quantity:true },
  { emoji:'🍔', name:'Hambúrguer', description:'Caprichado, do jeitinho que você gosta', quantity:true },
  { emoji:'🎬', name:'Filme depois do jogo', description:'Você escolhe o filme', quantity:false },
  { emoji:'🧸', name:'Cobertor', description:'Para ficar bem juntinho', quantity:false },
  { emoji:'🤗', name:'Abraços', description:'Quantidade ilimitada', quantity:false },
  { emoji:'💋', name:'Beijinhos', description:'O melhor item do cardápio', quantity:false }
];
const themes={game:'🇧🇷 Dia de jogo',movie:'🎬 Cinema em casa',dinner:'🍝 Jantar a dois',picnic:'🧺 Piquenique',surprise:'✨ Surpresa romântica'};
const state={offered:new Set(['Batata frita','Refrigerante','Chocolate','Filme depois do jogo','Cobertor','Abraços','Beijinhos']),draft:{},current:null,order:{}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const safe=text=>{const el=document.createElement('div');el.textContent=text;return el.innerHTML};

function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
$('#date').value=tomorrow();
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`)?.classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.body.classList.toggle('guest-mode',['received','success','declined','notFound'].includes(name));window.scrollTo({top:0,behavior:'smooth'});if(name==='history')renderHistory()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));

function itemInfo(name){return baseItems.find(i=>i.name===name)||{emoji:'💛',name,description:'Um detalhe escolhido com carinho',quantity:true}}
function renderCreatorItems(){const extras=[...state.offered].filter(name=>!baseItems.some(i=>i.name===name)).map(name=>itemInfo(name));const all=[...baseItems,...extras];$('#itemsGrid').innerHTML=all.map(item=>`<button type="button" class="item-option ${state.offered.has(item.name)?'selected':''}" data-name="${safe(item.name)}"><span>${item.emoji}</span><strong>${safe(item.name)}</strong><small>${safe(item.description)}</small></button>`).join('');$('#selectedCount').textContent=state.offered.size;$$('.item-option').forEach(b=>b.onclick=()=>{state.offered.has(b.dataset.name)?state.offered.delete(b.dataset.name):state.offered.add(b.dataset.name);renderCreatorItems()})}
renderCreatorItems();
$('#toItems').onclick=()=>{if(!$('#inviteForm').reportValidity())return;state.draft={title:$('#title').value.trim(),message:$('#message').value.trim(),date:$('#date').value,time:$('#time').value,location:$('#location').value.trim(),theme:$('#theme').value};showView('items')};
$('#addCustom').onclick=()=>{const value=$('#customItem').value.trim();if(!value)return;state.offered.add(value);$('#customItem').value='';renderCreatorItems();toast('Opção adicionada ao cardápio 💛')};
$('#customItem').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#addCustom').click()}};

function invites(){try{return JSON.parse(localStorage.getItem('combinado-invites')||'[]')}catch{return[]}}
function saveInvites(list){localStorage.setItem('combinado-invites',JSON.stringify(list))}
function formatDate(date,time){return new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date(`${date}T${time}`))+' · '+time}
function inviteUrl(invite){return location.protocol==='file:'?`/convite/${invite.code}`:`${location.origin}/convite/${invite.code}`}

$('#finishInvite').onclick=async()=>{if(!state.offered.size){toast('Adicione pelo menos uma opção ao cardápio ✨');return}const button=$('#finishInvite');button.disabled=true;button.textContent='Criando convite...';try{const response=await fetch('/api/invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state.draft,items:[...state.offered]})});const data=await response.json();if(!response.ok)throw new Error(data.error);const invite=data.invite;const list=invites();list.unshift(invite);saveInvites(list);state.current=invite;$('#shareLink').value=inviteUrl(invite);showView('share')}catch(error){toast(error.message||'Não foi possível criar o convite')}finally{button.disabled=false;button.innerHTML='Gerar convite <span>→</span>'}};
$('#copyLink').onclick=async()=>{try{await navigator.clipboard.writeText($('#shareLink').value);toast('Link copiado! Agora é só enviar 💌')}catch{$('#shareLink').select();document.execCommand('copy');toast('Link copiado! 💌')}};
$('#previewInvite').onclick=()=>{openInvite(state.current)};

function openInvite(invite){state.current=invite;state.order={};$('#receivedTitle').textContent=invite.title;$('#receivedDate').textContent=formatDate(invite.date,invite.time);$('#receivedLocation').textContent=invite.location;$('#confirmDate').textContent=formatDate(invite.date,invite.time);$('#confirmLocation').textContent=invite.location;$('#receivedTheme').textContent=themes[invite.theme]||'NOSSO MOMENTINHO';renderGuestMenu();showGuestStep(1);showView('received')}
function renderGuestMenu(){const items=state.current.items.map(itemInfo);$('#guestMenu').innerHTML=items.map(item=>{const qty=state.order[item.name]||0;return `<article class="guest-item ${qty?'selected':''}"><div class="guest-emoji">${item.emoji}</div><div class="guest-copy"><strong>${safe(item.name)}</strong><small>${safe(item.description)}</small></div>${qty?`<div class="stepper"><button data-action="minus" data-name="${safe(item.name)}">−</button><b>${qty}</b><button data-action="plus" data-name="${safe(item.name)}">+</button></div>`:`<button class="add-item" data-action="plus" data-name="${safe(item.name)}">Adicionar</button>`}</article>`}).join('');$$('[data-action]').forEach(b=>b.onclick=()=>{const name=b.dataset.name;const max=itemInfo(name).quantity?9:1;state.order[name]=Math.max(0,Math.min(max,(state.order[name]||0)+(b.dataset.action==='plus'?1:-1)));if(!state.order[name])delete state.order[name];renderGuestMenu();renderOrder()});renderOrder()}
function renderOrder(){const entries=Object.entries(state.order);$('#chosenCount').textContent=entries.reduce((sum,[,qty])=>sum+qty,0);$('#orderLines').innerHTML=entries.map(([name,qty])=>{const item=itemInfo(name);return `<span class="confirm-line"><i>${item.emoji}</i><strong>${safe(name)}</strong><b>${qty}x</b></span>`}).join('')}
function showGuestStep(step){$$('.guest-step').forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===step));$('#stepLabel').textContent=`${step} / 3`;$('#progressFill').style.width=`${step/3*100}%`;window.scrollTo(0,0)}
$$('[data-next-step]').forEach(button=>button.onclick=()=>showGuestStep(Number(button.dataset.nextStep)));
$('#continueOrder').onclick=()=>{if(!Object.keys(state.order).length){toast('Escolha pelo menos uma coisinha 💛');return}showGuestStep(3)};
async function updateStatus(status){if(!state.current)return false;try{const response=await fetch(`/api/invites?code=${state.current.code}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,responseItems:Object.entries(state.order).map(([name,quantity])=>({name,quantity}))})});const data=await response.json();if(!response.ok)throw new Error(data.error);state.current=data.invite;const list=invites();const index=list.findIndex(i=>i.code===state.current.code);if(index>=0)list[index]=state.current;saveInvites(list);return true}catch(error){toast(error.message||'Não foi possível responder');return false}}
$('#acceptInvite').onclick=async()=>{if(!Object.keys(state.order).length){toast('Escolha pelo menos uma coisinha do cardápio 💛');return}if(await updateStatus('accepted'))showView('success')};
$('#declineInvite').onclick=async()=>{if(await updateStatus('declined'))showView('declined')};

async function renderHistory(filter='all'){let stored=invites();if(location.protocol!=='file:'&&stored.length){const synced=await Promise.all(stored.map(async local=>{try{const response=await fetch(`/api/invites?code=${local.code}`);return response.ok?(await response.json()).invite:local}catch{return local}}));stored=synced;saveInvites(stored)}const list=stored.filter(i=>filter==='all'||i.status===filter);const labels={pending:'Pendente',accepted:'Aceito',declined:'Recusado'};$('#historyList').innerHTML=list.length?list.map(i=>{const chosen=i.responseItems?.length?`<div class="history-choice"><small>ESCOLHAS DA PESSOA</small><div>${i.responseItems.map(x=>`<span>${itemInfo(x.name).emoji} ${safe(x.name)} · ${x.quantity}x</span>`).join('')}</div>${i.responseDate?`<time>Respondido em ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(i.responseDate))}</time>`:''}</div>`:'';return `<article class="history-item"><div class="history-main"><div class="history-emoji">${i.status==='accepted'?'💛':i.status==='declined'?'🌷':'💌'}</div><div class="history-copy"><h4>${safe(i.title)}</h4><small>${formatDate(i.date,i.time)} · ${safe(i.location)}</small></div><span class="status ${i.status}">${labels[i.status]}</span></div>${chosen}<div class="history-actions"><button data-copy-code="${i.code}">Copiar link</button></div></article>`}).join(''):'<div class="empty">Nenhum momentinho por aqui ainda.<br>Que tal criar o primeiro? 💛</div>';$$('[data-copy-code]').forEach(b=>b.onclick=async()=>{const invite=invites().find(i=>i.code===b.dataset.copyCode);await navigator.clipboard.writeText(inviteUrl(invite));toast('Link copiado 💌')})}
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderHistory(b.dataset.filter)});
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

async function bootFromLink(){const match=location.pathname.match(/\/(?:convite|c)\/([a-z0-9]{6})/i);const inviteCode=match?.[1];if(!inviteCode)return;try{const response=await fetch(`/api/invites?code=${inviteCode}`);if(response.status===404){showView('notFound');return}const data=await response.json();if(!response.ok)throw new Error(data.error);openInvite(data.invite)}catch{showView('notFound')}}
bootFromLink();
